#!/usr/bin/env node
import { open } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import readline from "node:readline/promises";
import { createReadStream } from "node:fs";
import { createVaultFile, listVaultFile, migrateVaultFile } from "./vault-host.mjs";
const usage = "Usage: csk vault <create|list|migrate> [options]\n\ncsk vault create --out PATH [--passphrase-fd FD] [--force]\ncsk vault list --vault PATH [--passphrase-fd FD] [--json]\ncsk vault migrate --input PATH --out PATH [--input-passphrase-fd FD] [--passphrase-fd FD] [--force]\n";
const bad = () => { throw Error("Vault arguments are invalid."); };
const parse = (args) => { if (args.includes("--help") || args.includes("-h")) return { help: true }; const [group, command, ...rest] = args; const allowed = { create: ["--out", "--passphrase-fd", "--force"], list: ["--vault", "--passphrase-fd", "--json"], migrate: ["--input", "--out", "--input-passphrase-fd", "--passphrase-fd", "--force"] }; if (group !== "vault" || !allowed[command]) bad(); const o = { command }; for (let i = 0; i < rest.length; i += 1) { const key = rest[i]; if (!allowed[command].includes(key) || o[key.slice(2)] !== undefined) bad(); if (["--force", "--json"].includes(key)) o[key.slice(2)] = true; else if (rest[i + 1] && !rest[i + 1].startsWith("--")) o[key.slice(2)] = rest[++i]; else bad(); } if ((command === "create" && !o.out) || (command === "list" && !o.vault) || (command === "migrate" && (!o.input || !o.out)) || [o["passphrase-fd"], o["input-passphrase-fd"]].filter(Boolean).some((fd) => !/^\d+$/.test(fd))) bad(); return o; };
const tty = async (prompt) => { const h = await open("/dev/tty", "r+"); const old = spawnSync("stty", ["-g"], { stdio: [h.fd, "pipe", "ignore"] }).stdout.toString().trim(); let closed = false; const close = async () => { if (!closed) { closed = true; await h.close(); } }; const restore = () => spawnSync("stty", [old], { stdio: [h.fd, "ignore", "ignore"] }); const codes = { SIGINT: 130, SIGTERM: 143, SIGHUP: 129 }; const handlers = Object.entries(codes).map(([signal, code]) => [signal, () => { restore(); close().finally(() => process.exit(code)); }]); handlers.forEach(([signal, handler]) => process.once(signal, handler)); try { spawnSync("stty", ["-echo"], { stdio: [h.fd, "ignore", "ignore"] }); const rl = readline.createInterface({ input: createReadStream("/dev/tty"), output: process.stderr }); const value = await rl.question(`${prompt}: `); rl.close(); process.stderr.write("\n"); return value; } finally { restore(); handlers.forEach(([signal, handler]) => process.removeListener(signal, handler)); await close(); } };
const fdText = (fd) => new Promise((resolve, reject) => { let text = ""; const input = createReadStream(null, { fd: Number(fd), autoClose: false }); input.on("data", (x) => { text += x; }); input.on("end", () => resolve(text.replace(/\r?\n$/, ""))); input.on("error", reject); });
try { const o = parse(process.argv.slice(2)); if (o.help) process.stdout.write(usage); else { const fds = [...new Set([o["input-passphrase-fd"], o["passphrase-fd"]].filter(Boolean))]; const values = new Map(await Promise.all(fds.map(async (fd) => [fd, (await fdText(fd)).split(/\r?\n/)]))); const take = async (fd, label) => { const value = fd ? values.get(fd).shift() : await tty(label); if (!value) throw Error("Vault passphrase input is invalid."); return value; }; if (o.command === "create") { const pass = await take(o["passphrase-fd"], "Vault passphrase"); const confirm = await take(o["passphrase-fd"], "Confirm vault passphrase"); if (pass !== confirm) throw Error("Vault passphrase confirmation failed."); await createVaultFile(o.out, pass, undefined, o.force); } else if (o.command === "list") { const entries = await listVaultFile(o.vault, await take(o["passphrase-fd"], "Vault passphrase")); process.stdout.write(o.json ? `${JSON.stringify(entries)}\n` : `${entries.map((x) => `${x.id}\t${x.kind}\t${x.label}\t${x.createdAt}`).join("\n")}\n`); } else await migrateVaultFile(o.input, o.out, await take(o["input-passphrase-fd"], "Input vault passphrase"), await take(o["passphrase-fd"], "Vault passphrase"), o.force); } } catch (error) { process.stderr.write(`${error.message?.startsWith("Vault ") ? error.message : "Vault input is invalid."}\n`); process.exitCode = 1; }
