name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-and-build:
    runs-on: nixos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check formatting
        run: nix run .#ci-check

      - name: Check Haskell quality
        run: nix run .#ci-haskell-quality

      - name: Check vectors
        run: nix run .#ci-check-vectors

      - name: Build app
        run: nix run .#ci-build

      - name: Build docs
        run: nix develop github:paolino/dev-assets?dir=mkdocs --quiet -c mkdocs build --strict

      - name: Run PureScript tests
        run: nix run .#ci-test

      - name: Run Playwright UI tests
        run: nix run .#ci-playwright
